version: "3.3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elastic
    restart: on-failure
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - rebuildnet
    volumes:
      - tracker_data:/usr/share/elasticsearch/data
    ports:
      - 9000:9200


networks:
  rebuildnet:
    driver: bridge

volumes:
  tracker_data:
    driver: local
