version: "2.0"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elastic
    restart: on-failure
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - rebuildnet
    #    ports:
    #      - 9000:9200
    volumes:
      - tracker_data:/usr/share/elasticsearch/data

  listener:
    build: .
    container_name: listener
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - elastic
    networks:
      - rebuildnet
    ports:
      - 9999:5000
    command: python device_to_elastic.py

  folium:
    build: .
    container_name: folium
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - elastic
    networks:
      - rebuildnet
    ports:
      - 8181:5000
    command: python serve_map_from_elastic.py

networks:
  rebuildnet:
    driver: bridge

volumes:
  tracker_data:
    driver: local
